name: Build Executables

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
        pip install ordered-set  # Nuitka 依赖
        pip install zstandard    # 用于压缩
    
    - name: Build with Nuitka
      run: |
        python -m nuitka --windows-console-mode=disable --onefile --enable-plugin=pyqt6 --windows-icon-from-ico=assets/icon.ico --follow-imports --output-dir=build --output-filename="OneDrive下载器-Windows.exe" gui.py
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: OneDrive下载器-Windows
        path: build/OneDrive下载器-Windows.exe
        
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
        pip install ordered-set  # Nuitka 依赖
        pip install zstandard    # 用于压缩
        sudo apt-get update
        sudo apt-get install -y patchelf  # Linux 构建需要
        
    - name: Build with Nuitka
      run: |
        python -m nuitka --onefile --enable-plugin=pyqt6 --linux-icon=assets/icon-256.png --include-package=requests --follow-imports --output-dir=build --output-filename="OneDrive下载器-Linux" gui.py
    
    - name: Upload Linux executable
      uses: actions/upload-artifact@v3
      with:
        name: OneDrive下载器-Linux
        path: build/OneDrive下载器-Linux
        
  create-release-assets:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create release assets
      run: |
        mkdir -p release
        cp OneDrive下载器-Windows/OneDrive下载器-Windows.exe release/
        cp OneDrive下载器-Linux/OneDrive下载器-Linux release/
        cp OneDrive下载器.desktop release/
        mkdir -p release/assets
        cp -r assets/* release/assets/
        
    - name: Upload release assets
      uses: actions/upload-artifact@v3
      with:
        name: release-assets
        path: release/ 