name: Build Executables

on:
  push:
    branches: [dev]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka ordered-set zstandard
    
    - name: Build Windows executable
      run: |
        python -m nuitka `
          --windows-console-mode=disable `
          --onefile `
          --enable-plugin=pyqt6 `
          --windows-icon-from-ico=assets/icon.ico `
          --follow-imports `
          --output-dir=build `
          --output-filename="OneDrive下载器-Windows.exe" `
          gui.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: OneDrive下载器-Windows
        path: build/OneDrive下载器-Windows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y patchelf
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka ordered-set zstandard
    
    - name: Build Linux executable
      run: |
        python -m nuitka \
          --onefile \
          --enable-plugin=pyqt6 \
          --linux-icon=assets/icon-256.png \
          --include-package=requests \
          --follow-imports \
          --output-dir=build \
          --output-filename="OneDrive下载器-Linux" \
          gui.py
    
    - name: Make executable
      run: chmod +x build/OneDrive下载器-Linux
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: OneDrive下载器-Linux
        path: build/OneDrive下载器-Linux 